baseURL = "http://blog.chrispotter.io"
languageCode = "en-us"
title = "blog.chrispotter.io"
theme = "minimal"

[params]
    author = "Chris Potter"
    description = "ramblings about stuff I do"
    githubUsername = "chrispotter"
    accent = "green"
    showBorder = false
    backgroundColor = "white"
    font = "Roboto" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "darcula"
    highlightLanguages = ["go", "php", "json", "python", "javascript"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/code"
    name = "Code"
    weight = 2

[[menu.main]]
    url = "/wood"
    name = "Wood"
    weight = 3

[[menu.main]]
    url = "/3dprinting"
    name = "3d Printing"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

# [[menu.icon]]
#     url = "mailto:me@example.com"
#     name = "envelope-o"
#     weight = 1

[[menu.icon]]
    url = "https://github.com/chrispotter/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://www.linkedin.com/in/chris-potter-86428216/"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://chrispotter.io"
    name = "home"
    weight = 5
